import { createClient, configureChains, defaultChains, WagmiConfig, mainnet } from 'wagmi';
import { publicProvider } from 'wagmi/providers/public';
import { ChainId, ThirdwebProvider } from '@thirdweb-dev/react';
import Head from "next/head";
import "../styles/globals.css";

 
const { provider, webSocketProvider } = configureChains(
  [mainnet, polygon, bsc],
  [publicProvider()],
)
 
const client = createClient({
  provider,
  webSocketProvider,
})

// This is the chainId your dApp will work on.
const activeChainId = ChainId.Mainnet;

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <ThirdwebProvider desiredChainId={activeChainId}>
      <Head>
        <title> Trust Wallet Dashboard </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WagmiConfig client={client}>
        <Component {...pageProps} />
      </WagmiConfig>
    </ThirdwebProvider>
  </div>
  );
}

export default MyApp
